### ISSUE TITLE
exec: "run.sh" problem running docker

### ISSUE THREAD

**Issue by tacman** [kickasssubtitles/kickasssubtitles#1]
I'm following the README instructions, and having an issue running docker-compose up:

```
docker-compose up
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied
```

So I try with sudo instead:

```
Starting kickasssubtitles_app ... error

ERROR: for kickasssubtitles_app  Cannot start service app: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "run.sh": executable file not found in $PATH: unknown

ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "run.sh": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```

I'm running PopOS (Ubuntu) 21.04.

Googling this error, it seems to be something with bash, but I'm hesitant to blindly follow some of the solutions for fear to doing something to my normal environment.  Any suggestions?

Thanks,

Tac

**Comment by grzesw** [comment]
@tacman have you managed to solve the issue? :)

**Comment by tacman** [comment]
The original issue was related to permissions.  After I fixed that, it got very close to finishing, but the final command fails:

```
Creating kickasssubtitles_app     ... error

ERROR: for kickasssubtitles_app  Cannot start service app: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "run.sh": executable file not found in $PATH: unknown

ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "run.sh": executable file not found in $PATH: unknown
```

**Comment by tacman** [comment]
There appears to be a problem installing composer.  That problem appears to
be preg_match failing, perhaps having something to do with PRCE.

The docker setup is pretty sophisticated, most symfony apps have a php-fpm
container.  My docker skills are minimal, of course I want to learn more,
so I'm diving in and attempting upgrades, hoping to solve this.  Any
pointers?

Thanks.

**Comment by grzesw** [comment]
okay. i think the problem is that the file `run.sh` needs to be marked executable - you need to do: `chmod +x run.sh` and try again. if it works you can create PR which adds executable bit to this file (as GIT stores also permissions for files)

let me know if this worked

**Comment by tacman** [comment]
i don't think it's that, i don't think composer is being installed.

**Comment by grzesw** [comment]
@tacman right, yea there is some issues with debian php packages: https://github.com/composer/composer/issues/10294

i applied temporary solution, you can pull latest changes and try again it seems to be working on my side
